// Hash/signature/encoding parity between app/vendor/safe and @safe-global/protocol-kit v6.
//
// Fixtures in tests/fixtures/safe-parity-fixtures.json were generated by running
// protocol-kit 6.1.0 against anvil (anvil-safe-state.json) before the dependency was
// removed. These hashes are identity keys for routes, localStorage, and share links —
// any mismatch here means existing user data becomes unreachable.
//
// Requires anvil on :8545 (started by tests/scripts/start-anvil-and-test.sh).

import { test, expect } from "@playwright/test";
import { createWalletClient, http } from "viem";
import { privateKeyToAccount } from "viem/accounts";
import { SafeAccount } from "../app/vendor/safe/account";
import { SafeTransaction } from "../app/vendor/safe/transaction";
import { SafeSignature, buildSignatureBytes, generatePreValidatedSignature } from "../app/vendor/safe/signatures";
import {
  calculateSafeMessageLookupHash,
  calculateSafeTransactionHash,
  safeMessageTypedData,
  safeTxTypedData,
} from "../app/vendor/safe/hashing";
import { encodeMultiSendCall } from "../app/vendor/safe/multisend";
import {
  buildSafeDeploymentTransaction,
  encodeSetupCallData,
  getChainSpecificDefaultSaltNonce,
} from "../app/vendor/safe/deployment";
import {
  getDefaultContractAddresses,
  getKnownChainSafeVersion,
  isOfficialDeployment,
  getUntrustedContracts,
} from "../app/vendor/safe/deployments";
import type { EIP712TypedData, SafeTransactionData } from "../app/vendor/safe/types";
import { readFileSync } from "node:fs";

const fixtures = JSON.parse(readFileSync(new URL("./fixtures/safe-parity-fixtures.json", import.meta.url), "utf8"));

const RPC = "http://127.0.0.1:8545";
const CHAIN_ID = 31337;
const SAFE_VERSION = "1.4.1";

const ACCT0 = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266";
const PK0 = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" as const;
const ACCT1 = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8";
const PK1 = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d" as const;
const ACCT2 = "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC";

const LOCAL_CONTRACT_NETWORKS = {
  [String(CHAIN_ID)]: {
    safeSingletonAddress: "0x41675C099F32341bf84BFc5382aF534df5C7461a",
    safeProxyFactoryAddress: "0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67",
    multiSendAddress: "0x38869bf66a61cF6bDB996A6aE40D5853Fd43B526",
    multiSendCallOnlyAddress: "0x9641d764fc13c8B624c04430C7356C1C7C8102e2",
    fallbackHandlerAddress: "0xfd0732Dc9E303f09fCEf3a7388Ad10A83459Ec99",
  },
};

const SAFE = fixtures.predictedAddress as `0x${string}`;

const predictedConfig = {
  provider: RPC,
  signer: ACCT0,
  predictedSafe: {
    safeAccountConfig: { owners: [ACCT0, ACCT1, ACCT2], threshold: 2 },
    safeDeploymentConfig: { saltNonce: "12345" },
  },
  contractNetworks: LOCAL_CONTRACT_NETWORKS,
};

/** Deploy the fixture Safe on anvil if a previous test/run hasn't already. */
async function ensureFixtureSafeDeployed(): Promise<void> {
  const predicted = await SafeAccount.init(predictedConfig);
  if (await predicted.isSafeDeployed()) return;
  const deployTx = await predicted.createSafeDeploymentTransaction();
  const wallet = createWalletClient({ account: privateKeyToAccount(PK0), transport: http(RPC) });
  const hash = await wallet.sendTransaction({
    to: deployTx.to as `0x${string}`,
    value: BigInt(deployTx.value),
    data: deployTx.data as `0x${string}`,
    chain: null,
  });
  await predicted.publicClient.waitForTransactionReceipt({ hash });
}

test.describe("protocol-kit parity", () => {
  test("SafeTx hashes match protocol-kit", () => {
    const cases: Array<[SafeTransactionData, string]> = [
      [fixtures.createTransactionSingle.data, fixtures.transactionHashSingle],
      [fixtures.createTransactionBatch.data, fixtures.transactionHashBatch],
    ];
    for (const [data, expected] of cases) {
      expect(calculateSafeTransactionHash(SAFE, data, SAFE_VERSION, CHAIN_ID)).toBe(expected);
    }
  });

  test("MultiSend batch encoding matches protocol-kit", () => {
    const batch = [
      { to: ACCT1, value: "123456", data: "0x" },
      { to: ACCT2, value: "0", data: "0xdeadbeef", operation: 0 },
    ];
    expect(encodeMultiSendCall(batch)).toBe(fixtures.createTransactionBatch.data.data);
  });

  test("signature encoding sorts by signer and handles contract signatures", () => {
    // Two ECDSA signatures, insertion order reversed vs address order
    const tx = new SafeTransaction(fixtures.signTransaction.txData);
    for (const sig of fixtures.signTransaction.signatures) {
      tx.addSignature(new SafeSignature(sig.signer, sig.data, sig.isContractSignature));
    }
    expect(Array.from(tx.signatures.keys())).toEqual(fixtures.signTransaction.signatureMapKeys);
    expect(tx.encodedSignatures()).toBe(fixtures.signTransaction.encodedSignatures);

    // ECDSA + EIP-1271 contract signature (static/dynamic parts, offsets)
    const mixed = buildSignatureBytes([
      new SafeSignature(ACCT2, "0x" + "11".repeat(64) + "1f", false),
      new SafeSignature(ACCT0, "0x" + "22".repeat(65), true),
    ]);
    expect(mixed).toBe(fixtures.buildSignatureBytesMixed);
  });

  test("pre-validated signature format matches protocol-kit", () => {
    const sig = generatePreValidatedSignature(ACCT0);
    expect(sig.data).toBe(`0x000000000000000000000000${ACCT0.slice(2)}${"0".repeat(64)}01`);
  });

  test("message lookup hashes match protocol-kit (storage-key compatibility)", () => {
    expect(calculateSafeMessageLookupHash(SAFE, "hello world", SAFE_VERSION, CHAIN_ID)).toBe(
      fixtures.messageLookupHashString,
    );
    expect(calculateSafeMessageLookupHash(SAFE, "0xdeadbeef", SAFE_VERSION, CHAIN_ID)).toBe(
      fixtures.messageLookupHashHexNonUtf8,
    );
    expect(calculateSafeMessageLookupHash(SAFE, "0x68656c6c6f", SAFE_VERSION, CHAIN_ID)).toBe(
      fixtures.messageLookupHashHexUtf8,
    );
  });

  test("SafeTx signing payload reproduces protocol-kit signatures", async () => {
    const typedData = safeTxTypedData(SAFE, fixtures.signTransaction.txData, SAFE_VERSION, CHAIN_ID);
    const sig0 = await privateKeyToAccount(PK0).signTypedData(typedData as never);
    const sig1 = await privateKeyToAccount(PK1).signTypedData(typedData as never);
    expect(sig0).toBe(fixtures.signTransaction.signatures[0].data);
    expect(sig1).toBe(fixtures.signTransaction.signatures[1].data);
  });

  test("SafeMessage signing payload reproduces protocol-kit signatures", async () => {
    const account = privateKeyToAccount(PK0);
    const stringPayload = safeMessageTypedData(SAFE, "hello world", SAFE_VERSION, CHAIN_ID);
    expect(await account.signTypedData(stringPayload as never)).toBe(fixtures.signMessage.signatures[0].data);

    // Hex-looking strings are signed as literal UTF-8 text (protocol-kit quirk)
    const hexPayload = safeMessageTypedData(SAFE, "0xdeadbeef", SAFE_VERSION, CHAIN_ID);
    expect(await account.signTypedData(hexPayload as never)).toBe(fixtures.signMessageHexString.signature.data);

    // EIP-712 typed data messages sign their canonical inner hash
    const typedPayload = safeMessageTypedData(
      SAFE,
      fixtures.signMessageTypedData.input as EIP712TypedData,
      SAFE_VERSION,
      CHAIN_ID,
    );
    expect(await account.signTypedData(typedPayload as never)).toBe(fixtures.signMessageTypedData.signature.data);
  });

  test("deployment registry: defaults and chain-scoped trust", () => {
    // Standard chains default to the canonical v1.4.1 deterministic deployment
    const anvilDefaults = getDefaultContractAddresses(31337);
    expect(anvilDefaults.safeSingletonAddress).toBe("0x41675C099F32341bf84BFc5382aF534df5C7461a");
    expect(anvilDefaults.safeProxyFactoryAddress).toBe("0x4e1DCf7AD4e460CfD30791CCC4F9c8a4f820ec67");

    // BattleChain (626) defaults to its registered v1.5.0 suite
    expect(getKnownChainSafeVersion(626)).toBe("1.5.0");
    const battlechainDefaults = getDefaultContractAddresses(626);
    expect(battlechainDefaults.safeSingletonAddress).toBe("0xFF716747B4D28EAE844Dc069387C9bFC00e51737");
    expect(battlechainDefaults.safeProxyFactoryAddress).toBe("0x8d0D56f72E266a4BfA05340f68409dEBbdbdc9e2");
    expect(battlechainDefaults.multiSendCallOnlyAddress).toBe("0xed4c81c91602CDD5c1e396a1AF28735E03EdA9e2");
    expect(battlechainDefaults.simulateTxAccessorAddress).toBeUndefined();
    expect(getUntrustedContracts(battlechainDefaults, 626)).toEqual([]);

    // BattleChain addresses are trusted ONLY on chain 626
    const bcSingleton = "0xFF716747B4D28EAE844Dc069387C9bFC00e51737";
    expect(isOfficialDeployment("safeSingletonAddress", bcSingleton, 626)).toBe(true);
    expect(isOfficialDeployment("safeSingletonAddress", bcSingleton, 1)).toBe(false);
    expect(isOfficialDeployment("safeSingletonAddress", bcSingleton)).toBe(false);

    // SafeL2 and ExtensibleFallbackHandler alternates are trusted on 626
    expect(isOfficialDeployment("safeSingletonAddress", "0xb6524C4fBcEd314EAad98Bc750B6AD76B64d7f8A", 626)).toBe(true);
    expect(isOfficialDeployment("fallbackHandlerAddress", "0x115b290ecDe805FD846E0C347f3419A4234Fd673", 626)).toBe(
      true,
    );

    // Canonical deployments are trusted on every chain (case-insensitive)
    expect(isOfficialDeployment("safeSingletonAddress", anvilDefaults.safeSingletonAddress!.toLowerCase(), 626)).toBe(
      true,
    );
    // v1.5.0 canonical addresses are trusted too
    expect(isOfficialDeployment("safeSingletonAddress", "0xFf51A5898e281Db6DfC7855790607438dF2ca44b", 1)).toBe(true);
    // Arbitrary addresses are not
    expect(isOfficialDeployment("multiSendAddress", ACCT0, 626)).toBe(false);
  });

  test("deployment-trust gate: batching and creation refuse unknown contracts", async () => {
    await ensureFixtureSafeDeployed();
    const SIGN_MESSAGE_LIB = "0xd53cd0aB83D845Ac265BE939c57F53AD838012c9"; // has code on anvil, wrong role
    const CODELESS = "0x1111111111111111111111111111111111111111";
    const COPY_TARGET = "0x2222222222222222222222222222222222222222";
    const batch = [
      { to: ACCT1, value: "1", data: "0x" },
      { to: ACCT2, value: "2", data: "0x" },
    ];

    const initWith = (multiSendCallOnlyAddress: string, confirmedDeployments?: { multiSendCallOnlyAddress: string }) =>
      SafeAccount.init({
        provider: RPC,
        signer: ACCT0,
        safeAddress: SAFE,
        contractNetworks: {
          [String(CHAIN_ID)]: { ...LOCAL_CONTRACT_NETWORKS[String(CHAIN_ID)], multiSendCallOnlyAddress },
        },
        ...(confirmedDeployments && { confirmedDeployments }),
      });

    // codeless MultiSendCallOnly: hard refusal, even when user-confirmed
    const codeless = await initWith(CODELESS, { multiSendCallOnlyAddress: CODELESS });
    await expect(codeless.createTransaction({ transactions: batch, options: { nonce: 0 } })).rejects.toThrow(
      /has no code/,
    );

    // unknown-but-deployed contract: refused without confirmation, allowed with it
    const unknown = await initWith(SIGN_MESSAGE_LIB);
    await expect(unknown.createTransaction({ transactions: batch, options: { nonce: 0 } })).rejects.toThrow(
      /not a verified Safe deployment/,
    );
    const confirmed = await initWith(SIGN_MESSAGE_LIB, { multiSendCallOnlyAddress: SIGN_MESSAGE_LIB });
    const confirmedTx = await confirmed.createTransaction({ transactions: batch, options: { nonce: 0 } });
    expect(confirmedTx.data.to).toBe(SIGN_MESSAGE_LIB);

    // official bytecode at a custom address: auto-verified, no confirmation needed
    const officialCode = await confirmed.publicClient.getCode({
      address: LOCAL_CONTRACT_NETWORKS[String(CHAIN_ID)].multiSendCallOnlyAddress as `0x${string}`,
    });
    await confirmed.publicClient.request({
      method: "anvil_setCode" as any,
      params: [COPY_TARGET, officialCode] as never,
    });
    const verified = await initWith(COPY_TARGET);
    const verifiedTx = await verified.createTransaction({ transactions: batch, options: { nonce: 0 } });
    expect(verifiedTx.data.to).toBe(COPY_TARGET);

    // Safe creation: refuse a singleton nobody can vouch for
    const badCreation = await SafeAccount.init({
      provider: RPC,
      signer: ACCT0,
      predictedSafe: { safeAccountConfig: { owners: [ACCT0], threshold: 1 } },
      contractNetworks: {
        [String(CHAIN_ID)]: { ...LOCAL_CONTRACT_NETWORKS[String(CHAIN_ID)], safeSingletonAddress: CODELESS },
      },
    });
    await expect(badCreation.createSafeDeploymentTransaction()).rejects.toThrow(/has no code/);
  });

  test("default salt nonce derivation matches protocol-kit", () => {
    // Derivation is keccak256(utf8(PREDETERMINED_SALT_NONCE + chainId)); pinned implicitly
    // by the predictedAddressDefaultSalt fixture below, and explicitly stable here.
    expect(getChainSpecificDefaultSaltNonce(31337)).toMatch(/^0x[0-9a-f]{64}$/);
    expect(getChainSpecificDefaultSaltNonce(31337)).not.toBe(getChainSpecificDefaultSaltNonce(626));
  });

  test("CREATE2 prediction and deployment calldata match protocol-kit", async () => {
    const account = await SafeAccount.init(predictedConfig);
    expect(await account.getAddress()).toBe(fixtures.predictedAddress);

    // Pure calldata construction (independent of whether the Safe is already on-chain)
    const initializer = encodeSetupCallData(
      { owners: [ACCT0, ACCT1, ACCT2], threshold: 2 },
      LOCAL_CONTRACT_NETWORKS[String(CHAIN_ID)].fallbackHandlerAddress,
    );
    const deployTx = buildSafeDeploymentTransaction(
      LOCAL_CONTRACT_NETWORKS[String(CHAIN_ID)].safeProxyFactoryAddress,
      LOCAL_CONTRACT_NETWORKS[String(CHAIN_ID)].safeSingletonAddress,
      initializer,
      "12345",
    );
    expect(deployTx).toEqual(fixtures.deploymentTransaction);

    const defaultSaltAccount = await SafeAccount.init({
      ...predictedConfig,
      predictedSafe: { safeAccountConfig: { owners: [ACCT0, ACCT1, ACCT2], threshold: 2 } },
    });
    expect(await defaultSaltAccount.getAddress()).toBe(fixtures.predictedAddressDefaultSalt);
  });

  test("deployed Safe reads, createTransaction, and anvil-signed signatures match", async () => {
    await ensureFixtureSafeDeployed();

    const account = await SafeAccount.init({
      provider: RPC,
      signer: ACCT0,
      safeAddress: SAFE,
      contractNetworks: LOCAL_CONTRACT_NETWORKS,
    });
    expect(await account.getOwners()).toEqual(fixtures.safeInfo.owners);
    expect(await account.getThreshold()).toBe(fixtures.safeInfo.threshold);
    expect(account.getContractVersion()).toBe(fixtures.safeInfo.version);
    expect(await account.isOwner(ACCT0.toLowerCase())).toBe(true);

    const singleTx = await account.createTransaction({
      transactions: [{ to: ACCT1, value: "1000000000000000", data: "0x" }],
      options: { nonce: 7 },
    });
    expect(singleTx.data).toEqual(fixtures.createTransactionSingle.data);
    expect(await account.getTransactionHash(singleTx)).toBe(fixtures.transactionHashSingle);

    const batchTx = await account.createTransaction({
      transactions: [
        { to: ACCT1, value: "123456", data: "0x" },
        { to: ACCT2, value: "0", data: "0xdeadbeef", operation: 0 },
      ],
      options: { nonce: 3 },
    });
    expect(batchTx.data).toEqual(fixtures.createTransactionBatch.data);

    await expect(
      account.createTransaction({
        transactions: [
          { to: ACCT1, value: "0", data: "0x" },
          { to: ACCT2, value: "0", data: "0x", operation: 1 },
        ],
      }),
    ).rejects.toThrow(/DELEGATECALL/);

    // signTransaction through anvil's eth_signTypedData_v4 reproduces the exact signature
    const signed0 = await account.signTransaction(singleTx);
    const account1 = await SafeAccount.init({
      provider: RPC,
      signer: ACCT1,
      safeAddress: SAFE,
      contractNetworks: LOCAL_CONTRACT_NETWORKS,
    });
    const signed01 = await account1.signTransaction(signed0);
    expect(
      Array.from(signed01.signatures.values()).map((sig) => ({
        signer: sig.signer,
        data: sig.data,
        isContractSignature: sig.isContractSignature,
      })),
    ).toEqual(fixtures.signTransaction.signatures);
    expect(signed01.encodedSignatures()).toBe(fixtures.signTransaction.encodedSignatures);

    // getSafeMessageHash through the account (lookup-hash quirk preserved)
    expect(await account.getSafeMessageHash("hello world")).toBe(fixtures.messageLookupHashString);
  });
});
